#!/bin/bash
set -Eeuo pipefail

if ! command -v brew &>/dev/null; then
    /usr/bin/ruby -e "$(curl -fqsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brewfile=$(mktemp)
trap 'rm -f "$brewfile"' EXIT
curl -fqsSLo"$brewfile" https://raw.githubusercontent.com/Fleshgrinder/dotfiles/mac/Brewfile
brew bundle --all --file="$brewfile"

if [[ -d ~/.dotfiles ]]; then
    git fetch --quiet
    git reset --quiet --hard origin/mac
else
    git clone --branch mac --quiet --single-branch https://github.com/Fleshgrinder/dotfiles.git ~/.dotfiles
fi

mkdir -p ~/dotfiles/alias ~/dotfiles/env ~/dotfiles/functions

for f in ~/.dotfiles/home/*; do
    ln -is "$f" ~/"$(basename "$f")"
done

# shellcheck disable=SC1090
source ~/.dotfiles/installers/*
